// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxpSiZvefFsN3ys5lxBSa5feOeMUDmNoI',
    appId: '1:475492806546:web:8a4ceb618610437b0b5b4b',
    messagingSenderId: '475492806546',
    projectId: 'stms-backend',
    authDomain: 'stms-backend.firebaseapp.com',
    storageBucket: 'stms-backend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvWwxB6OLika4acLD6R35dqtjESILJNEQ',
    appId: '1:475492806546:android:02caa1e0f8faa1650b5b4b',
    messagingSenderId: '475492806546',
    projectId: 'stms-backend',
    storageBucket: 'stms-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAicex2cOF0IUFkIPJOf2whbdl_aloLe24',
    appId: '1:475492806546:ios:0d2bfbc5d9aa61cb0b5b4b',
    messagingSenderId: '475492806546',
    projectId: 'stms-backend',
    storageBucket: 'stms-backend.firebasestorage.app',
    iosBundleId: 'com.example.stmsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAicex2cOF0IUFkIPJOf2whbdl_aloLe24',
    appId: '1:475492806546:ios:0d2bfbc5d9aa61cb0b5b4b',
    messagingSenderId: '475492806546',
    projectId: 'stms-backend',
    storageBucket: 'stms-backend.firebasestorage.app',
    iosBundleId: 'com.example.stmsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxpSiZvefFsN3ys5lxBSa5feOeMUDmNoI',
    appId: '1:475492806546:web:32726cc70d7b421f0b5b4b',
    messagingSenderId: '475492806546',
    projectId: 'stms-backend',
    authDomain: 'stms-backend.firebaseapp.com',
    storageBucket: 'stms-backend.firebasestorage.app',
  );
}
